// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: armycode.proto

#include "armycode.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_armycode_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_armycode_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ArmyCodeAnnounce;
}  // namespace protobuf_armycode_2eproto
namespace com {
namespace yhsoftlab {
namespace app {
namespace cahelper {
namespace protobuf {
class ArmyCodeAnnounceDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ArmyCodeAnnounce>
      _instance;
} _ArmyCodeAnnounce_default_instance_;
class ArmyCodeReplyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ArmyCodeReply>
      _instance;
} _ArmyCodeReply_default_instance_;
}  // namespace protobuf
}  // namespace cahelper
}  // namespace app
}  // namespace yhsoftlab
}  // namespace com
namespace protobuf_armycode_2eproto {
static void InitDefaultsArmyCodeAnnounce() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::yhsoftlab::app::cahelper::protobuf::_ArmyCodeAnnounce_default_instance_;
    new (ptr) ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ArmyCodeAnnounce =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsArmyCodeAnnounce}, {}};

static void InitDefaultsArmyCodeReply() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::yhsoftlab::app::cahelper::protobuf::_ArmyCodeReply_default_instance_;
    new (ptr) ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeReply();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeReply::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ArmyCodeReply =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsArmyCodeReply}, {
      &protobuf_armycode_2eproto::scc_info_ArmyCodeAnnounce.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ArmyCodeAnnounce.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ArmyCodeReply.base);
}

}  // namespace protobuf_armycode_2eproto
namespace com {
namespace yhsoftlab {
namespace app {
namespace cahelper {
namespace protobuf {

// ===================================================================

void ArmyCodeAnnounce::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ArmyCodeAnnounce::kCodeFieldNumber;
const int ArmyCodeAnnounce::kFbidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ArmyCodeAnnounce::ArmyCodeAnnounce()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_armycode_2eproto::scc_info_ArmyCodeAnnounce.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
}
ArmyCodeAnnounce::ArmyCodeAnnounce(const ArmyCodeAnnounce& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  code_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.code().size() > 0) {
    code_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.code_);
  }
  fbid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.fbid().size() > 0) {
    fbid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fbid_);
  }
  // @@protoc_insertion_point(copy_constructor:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
}

void ArmyCodeAnnounce::SharedCtor() {
  code_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fbid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ArmyCodeAnnounce::~ArmyCodeAnnounce() {
  // @@protoc_insertion_point(destructor:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  SharedDtor();
}

void ArmyCodeAnnounce::SharedDtor() {
  code_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fbid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ArmyCodeAnnounce::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ArmyCodeAnnounce& ArmyCodeAnnounce::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_armycode_2eproto::scc_info_ArmyCodeAnnounce.base);
  return *internal_default_instance();
}


void ArmyCodeAnnounce::Clear() {
// @@protoc_insertion_point(message_clear_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fbid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ArmyCodeAnnounce::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_code()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->code().data(), static_cast<int>(this->code().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string fbid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fbid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->fbid().data(), static_cast<int>(this->fbid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  return false;
#undef DO_
}

void ArmyCodeAnnounce::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string code = 1;
  if (this->code().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->code().data(), static_cast<int>(this->code().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->code(), output);
  }

  // string fbid = 2;
  if (this->fbid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fbid().data(), static_cast<int>(this->fbid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->fbid(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
}

size_t ArmyCodeAnnounce::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string code = 1;
  if (this->code().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->code());
  }

  // string fbid = 2;
  if (this->fbid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fbid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ArmyCodeAnnounce::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ArmyCodeAnnounce*>(&from));
}

void ArmyCodeAnnounce::MergeFrom(const ArmyCodeAnnounce& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.code().size() > 0) {

    code_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.code_);
  }
  if (from.fbid().size() > 0) {

    fbid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fbid_);
  }
}

void ArmyCodeAnnounce::CopyFrom(const ArmyCodeAnnounce& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArmyCodeAnnounce::IsInitialized() const {
  return true;
}

void ArmyCodeAnnounce::Swap(ArmyCodeAnnounce* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ArmyCodeAnnounce::InternalSwap(ArmyCodeAnnounce* other) {
  using std::swap;
  code_.Swap(&other->code_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  fbid_.Swap(&other->fbid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string ArmyCodeAnnounce::GetTypeName() const {
  return "com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce";
}


// ===================================================================

void ArmyCodeReply::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ArmyCodeReply::kAnnouncesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ArmyCodeReply::ArmyCodeReply()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_armycode_2eproto::scc_info_ArmyCodeReply.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
}
ArmyCodeReply::ArmyCodeReply(const ArmyCodeReply& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      announces_(from.announces_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
}

void ArmyCodeReply::SharedCtor() {
}

ArmyCodeReply::~ArmyCodeReply() {
  // @@protoc_insertion_point(destructor:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  SharedDtor();
}

void ArmyCodeReply::SharedDtor() {
}

void ArmyCodeReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ArmyCodeReply& ArmyCodeReply::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_armycode_2eproto::scc_info_ArmyCodeReply.base);
  return *internal_default_instance();
}


void ArmyCodeReply::Clear() {
// @@protoc_insertion_point(message_clear_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  announces_.Clear();
  _internal_metadata_.Clear();
}

bool ArmyCodeReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce announces = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_announces()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  return false;
#undef DO_
}

void ArmyCodeReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce announces = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->announces_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1,
      this->announces(static_cast<int>(i)),
      output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
}

size_t ArmyCodeReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated .com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce announces = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->announces_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->announces(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ArmyCodeReply::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ArmyCodeReply*>(&from));
}

void ArmyCodeReply::MergeFrom(const ArmyCodeReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  announces_.MergeFrom(from.announces_);
}

void ArmyCodeReply::CopyFrom(const ArmyCodeReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArmyCodeReply::IsInitialized() const {
  return true;
}

void ArmyCodeReply::Swap(ArmyCodeReply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ArmyCodeReply::InternalSwap(ArmyCodeReply* other) {
  using std::swap;
  CastToBase(&announces_)->InternalSwap(CastToBase(&other->announces_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string ArmyCodeReply::GetTypeName() const {
  return "com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace cahelper
}  // namespace app
}  // namespace yhsoftlab
}  // namespace com
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce* Arena::CreateMaybeMessage< ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce >(Arena* arena) {
  return Arena::CreateInternal< ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeReply* Arena::CreateMaybeMessage< ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeReply >(Arena* arena) {
  return Arena::CreateInternal< ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeReply >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
