// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: armycode.proto

#ifndef PROTOBUF_INCLUDED_armycode_2eproto
#define PROTOBUF_INCLUDED_armycode_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_armycode_2eproto 

namespace protobuf_armycode_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_armycode_2eproto
namespace com {
namespace yhsoftlab {
namespace app {
namespace cahelper {
namespace protobuf {
class ArmyCodeAnnounce;
class ArmyCodeAnnounceDefaultTypeInternal;
extern ArmyCodeAnnounceDefaultTypeInternal _ArmyCodeAnnounce_default_instance_;
class ArmyCodeReply;
class ArmyCodeReplyDefaultTypeInternal;
extern ArmyCodeReplyDefaultTypeInternal _ArmyCodeReply_default_instance_;
}  // namespace protobuf
}  // namespace cahelper
}  // namespace app
}  // namespace yhsoftlab
}  // namespace com
namespace google {
namespace protobuf {
template<> ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce* Arena::CreateMaybeMessage<::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce>(Arena*);
template<> ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeReply* Arena::CreateMaybeMessage<::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeReply>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace com {
namespace yhsoftlab {
namespace app {
namespace cahelper {
namespace protobuf {

// ===================================================================

class ArmyCodeAnnounce : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce) */ {
 public:
  ArmyCodeAnnounce();
  virtual ~ArmyCodeAnnounce();

  ArmyCodeAnnounce(const ArmyCodeAnnounce& from);

  inline ArmyCodeAnnounce& operator=(const ArmyCodeAnnounce& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ArmyCodeAnnounce(ArmyCodeAnnounce&& from) noexcept
    : ArmyCodeAnnounce() {
    *this = ::std::move(from);
  }

  inline ArmyCodeAnnounce& operator=(ArmyCodeAnnounce&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ArmyCodeAnnounce& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArmyCodeAnnounce* internal_default_instance() {
    return reinterpret_cast<const ArmyCodeAnnounce*>(
               &_ArmyCodeAnnounce_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ArmyCodeAnnounce* other);
  friend void swap(ArmyCodeAnnounce& a, ArmyCodeAnnounce& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ArmyCodeAnnounce* New() const final {
    return CreateMaybeMessage<ArmyCodeAnnounce>(NULL);
  }

  ArmyCodeAnnounce* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ArmyCodeAnnounce>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ArmyCodeAnnounce& from);
  void MergeFrom(const ArmyCodeAnnounce& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ArmyCodeAnnounce* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string code = 1;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  const ::std::string& code() const;
  void set_code(const ::std::string& value);
  #if LANG_CXX11
  void set_code(::std::string&& value);
  #endif
  void set_code(const char* value);
  void set_code(const char* value, size_t size);
  ::std::string* mutable_code();
  ::std::string* release_code();
  void set_allocated_code(::std::string* code);

  // string fbid = 2;
  void clear_fbid();
  static const int kFbidFieldNumber = 2;
  const ::std::string& fbid() const;
  void set_fbid(const ::std::string& value);
  #if LANG_CXX11
  void set_fbid(::std::string&& value);
  #endif
  void set_fbid(const char* value);
  void set_fbid(const char* value, size_t size);
  ::std::string* mutable_fbid();
  ::std::string* release_fbid();
  void set_allocated_fbid(::std::string* fbid);

  // @@protoc_insertion_point(class_scope:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr code_;
  ::google::protobuf::internal::ArenaStringPtr fbid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_armycode_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ArmyCodeReply : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply) */ {
 public:
  ArmyCodeReply();
  virtual ~ArmyCodeReply();

  ArmyCodeReply(const ArmyCodeReply& from);

  inline ArmyCodeReply& operator=(const ArmyCodeReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ArmyCodeReply(ArmyCodeReply&& from) noexcept
    : ArmyCodeReply() {
    *this = ::std::move(from);
  }

  inline ArmyCodeReply& operator=(ArmyCodeReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ArmyCodeReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArmyCodeReply* internal_default_instance() {
    return reinterpret_cast<const ArmyCodeReply*>(
               &_ArmyCodeReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ArmyCodeReply* other);
  friend void swap(ArmyCodeReply& a, ArmyCodeReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ArmyCodeReply* New() const final {
    return CreateMaybeMessage<ArmyCodeReply>(NULL);
  }

  ArmyCodeReply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ArmyCodeReply>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ArmyCodeReply& from);
  void MergeFrom(const ArmyCodeReply& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ArmyCodeReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce announces = 1;
  int announces_size() const;
  void clear_announces();
  static const int kAnnouncesFieldNumber = 1;
  ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce* mutable_announces(int index);
  ::google::protobuf::RepeatedPtrField< ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce >*
      mutable_announces();
  const ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce& announces(int index) const;
  ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce* add_announces();
  const ::google::protobuf::RepeatedPtrField< ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce >&
      announces() const;

  // @@protoc_insertion_point(class_scope:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce > announces_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_armycode_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ArmyCodeAnnounce

// string code = 1;
inline void ArmyCodeAnnounce::clear_code() {
  code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ArmyCodeAnnounce::code() const {
  // @@protoc_insertion_point(field_get:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
  return code_.GetNoArena();
}
inline void ArmyCodeAnnounce::set_code(const ::std::string& value) {
  
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
}
#if LANG_CXX11
inline void ArmyCodeAnnounce::set_code(::std::string&& value) {
  
  code_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
}
#endif
inline void ArmyCodeAnnounce::set_code(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
}
inline void ArmyCodeAnnounce::set_code(const char* value, size_t size) {
  
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
}
inline ::std::string* ArmyCodeAnnounce::mutable_code() {
  
  // @@protoc_insertion_point(field_mutable:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
  return code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ArmyCodeAnnounce::release_code() {
  // @@protoc_insertion_point(field_release:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
  
  return code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ArmyCodeAnnounce::set_allocated_code(::std::string* code) {
  if (code != NULL) {
    
  } else {
    
  }
  code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), code);
  // @@protoc_insertion_point(field_set_allocated:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
}

// string fbid = 2;
inline void ArmyCodeAnnounce::clear_fbid() {
  fbid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ArmyCodeAnnounce::fbid() const {
  // @@protoc_insertion_point(field_get:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
  return fbid_.GetNoArena();
}
inline void ArmyCodeAnnounce::set_fbid(const ::std::string& value) {
  
  fbid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
}
#if LANG_CXX11
inline void ArmyCodeAnnounce::set_fbid(::std::string&& value) {
  
  fbid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
}
#endif
inline void ArmyCodeAnnounce::set_fbid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  fbid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
}
inline void ArmyCodeAnnounce::set_fbid(const char* value, size_t size) {
  
  fbid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
}
inline ::std::string* ArmyCodeAnnounce::mutable_fbid() {
  
  // @@protoc_insertion_point(field_mutable:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
  return fbid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ArmyCodeAnnounce::release_fbid() {
  // @@protoc_insertion_point(field_release:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
  
  return fbid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ArmyCodeAnnounce::set_allocated_fbid(::std::string* fbid) {
  if (fbid != NULL) {
    
  } else {
    
  }
  fbid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), fbid);
  // @@protoc_insertion_point(field_set_allocated:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
}

// -------------------------------------------------------------------

// ArmyCodeReply

// repeated .com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce announces = 1;
inline int ArmyCodeReply::announces_size() const {
  return announces_.size();
}
inline void ArmyCodeReply::clear_announces() {
  announces_.Clear();
}
inline ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce* ArmyCodeReply::mutable_announces(int index) {
  // @@protoc_insertion_point(field_mutable:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply.announces)
  return announces_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce >*
ArmyCodeReply::mutable_announces() {
  // @@protoc_insertion_point(field_mutable_list:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply.announces)
  return &announces_;
}
inline const ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce& ArmyCodeReply::announces(int index) const {
  // @@protoc_insertion_point(field_get:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply.announces)
  return announces_.Get(index);
}
inline ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce* ArmyCodeReply::add_announces() {
  // @@protoc_insertion_point(field_add:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply.announces)
  return announces_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce >&
ArmyCodeReply::announces() const {
  // @@protoc_insertion_point(field_list:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply.announces)
  return announces_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace cahelper
}  // namespace app
}  // namespace yhsoftlab
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_armycode_2eproto
