// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: armycode.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "armycode.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace yhsoftlab {
namespace app {
namespace cahelper {
namespace protobuf {
class ArmyCodeAnnounceDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ArmyCodeAnnounce> {
} _ArmyCodeAnnounce_default_instance_;
class ArmyCodeReplyDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ArmyCodeReply> {
} _ArmyCodeReply_default_instance_;

namespace protobuf_armycode_2eproto {


void TableStruct::Shutdown() {
  _ArmyCodeAnnounce_default_instance_.Shutdown();
  _ArmyCodeReply_default_instance_.Shutdown();
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _ArmyCodeAnnounce_default_instance_.DefaultConstruct();
  _ArmyCodeReply_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER

}  // namespace protobuf_armycode_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ArmyCodeAnnounce::kCodeFieldNumber;
const int ArmyCodeAnnounce::kFbidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ArmyCodeAnnounce::ArmyCodeAnnounce()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_armycode_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
}
ArmyCodeAnnounce::ArmyCodeAnnounce(const ArmyCodeAnnounce& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  code_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.code().size() > 0) {
    code_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.code_);
  }
  fbid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.fbid().size() > 0) {
    fbid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fbid_);
  }
  // @@protoc_insertion_point(copy_constructor:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
}

void ArmyCodeAnnounce::SharedCtor() {
  code_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fbid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

ArmyCodeAnnounce::~ArmyCodeAnnounce() {
  // @@protoc_insertion_point(destructor:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  SharedDtor();
}

void ArmyCodeAnnounce::SharedDtor() {
  code_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fbid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ArmyCodeAnnounce::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ArmyCodeAnnounce& ArmyCodeAnnounce::default_instance() {
  protobuf_armycode_2eproto::InitDefaults();
  return *internal_default_instance();
}

ArmyCodeAnnounce* ArmyCodeAnnounce::New(::google::protobuf::Arena* arena) const {
  ArmyCodeAnnounce* n = new ArmyCodeAnnounce;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ArmyCodeAnnounce::Clear() {
// @@protoc_insertion_point(message_clear_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fbid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool ArmyCodeAnnounce::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string code = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) ==
            static_cast<::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_code()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->code().data(), this->code().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string fbid = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) ==
            static_cast<::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fbid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->fbid().data(), this->fbid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  return false;
#undef DO_
}

void ArmyCodeAnnounce::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  // string code = 1;
  if (this->code().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->code().data(), this->code().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->code(), output);
  }

  // string fbid = 2;
  if (this->fbid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fbid().data(), this->fbid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->fbid(), output);
  }

  // @@protoc_insertion_point(serialize_end:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
}

size_t ArmyCodeAnnounce::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  size_t total_size = 0;

  // string code = 1;
  if (this->code().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->code());
  }

  // string fbid = 2;
  if (this->fbid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fbid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ArmyCodeAnnounce::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ArmyCodeAnnounce*>(&from));
}

void ArmyCodeAnnounce::MergeFrom(const ArmyCodeAnnounce& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.code().size() > 0) {

    code_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.code_);
  }
  if (from.fbid().size() > 0) {

    fbid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fbid_);
  }
}

void ArmyCodeAnnounce::CopyFrom(const ArmyCodeAnnounce& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArmyCodeAnnounce::IsInitialized() const {
  return true;
}

void ArmyCodeAnnounce::Swap(ArmyCodeAnnounce* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ArmyCodeAnnounce::InternalSwap(ArmyCodeAnnounce* other) {
  code_.Swap(&other->code_);
  fbid_.Swap(&other->fbid_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string ArmyCodeAnnounce::GetTypeName() const {
  return "com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ArmyCodeAnnounce

// string code = 1;
void ArmyCodeAnnounce::clear_code() {
  code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& ArmyCodeAnnounce::code() const {
  // @@protoc_insertion_point(field_get:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
  return code_.GetNoArena();
}
void ArmyCodeAnnounce::set_code(const ::std::string& value) {
  
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
}
#if LANG_CXX11
void ArmyCodeAnnounce::set_code(::std::string&& value) {
  
  code_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
}
#endif
void ArmyCodeAnnounce::set_code(const char* value) {
  
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
}
void ArmyCodeAnnounce::set_code(const char* value, size_t size) {
  
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
}
::std::string* ArmyCodeAnnounce::mutable_code() {
  
  // @@protoc_insertion_point(field_mutable:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
  return code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ArmyCodeAnnounce::release_code() {
  // @@protoc_insertion_point(field_release:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
  
  return code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ArmyCodeAnnounce::set_allocated_code(::std::string* code) {
  if (code != NULL) {
    
  } else {
    
  }
  code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), code);
  // @@protoc_insertion_point(field_set_allocated:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.code)
}

// string fbid = 2;
void ArmyCodeAnnounce::clear_fbid() {
  fbid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& ArmyCodeAnnounce::fbid() const {
  // @@protoc_insertion_point(field_get:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
  return fbid_.GetNoArena();
}
void ArmyCodeAnnounce::set_fbid(const ::std::string& value) {
  
  fbid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
}
#if LANG_CXX11
void ArmyCodeAnnounce::set_fbid(::std::string&& value) {
  
  fbid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
}
#endif
void ArmyCodeAnnounce::set_fbid(const char* value) {
  
  fbid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
}
void ArmyCodeAnnounce::set_fbid(const char* value, size_t size) {
  
  fbid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
}
::std::string* ArmyCodeAnnounce::mutable_fbid() {
  
  // @@protoc_insertion_point(field_mutable:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
  return fbid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ArmyCodeAnnounce::release_fbid() {
  // @@protoc_insertion_point(field_release:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
  
  return fbid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ArmyCodeAnnounce::set_allocated_fbid(::std::string* fbid) {
  if (fbid != NULL) {
    
  } else {
    
  }
  fbid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), fbid);
  // @@protoc_insertion_point(field_set_allocated:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce.fbid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ArmyCodeReply::kAnnouncesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ArmyCodeReply::ArmyCodeReply()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_armycode_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
}
ArmyCodeReply::ArmyCodeReply(const ArmyCodeReply& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      announces_(from.announces_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
}

void ArmyCodeReply::SharedCtor() {
  _cached_size_ = 0;
}

ArmyCodeReply::~ArmyCodeReply() {
  // @@protoc_insertion_point(destructor:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  SharedDtor();
}

void ArmyCodeReply::SharedDtor() {
}

void ArmyCodeReply::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ArmyCodeReply& ArmyCodeReply::default_instance() {
  protobuf_armycode_2eproto::InitDefaults();
  return *internal_default_instance();
}

ArmyCodeReply* ArmyCodeReply::New(::google::protobuf::Arena* arena) const {
  ArmyCodeReply* n = new ArmyCodeReply;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ArmyCodeReply::Clear() {
// @@protoc_insertion_point(message_clear_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  announces_.Clear();
}

bool ArmyCodeReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce announces = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) ==
            static_cast<::google::protobuf::uint8>(10u)) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_announces()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  return false;
#undef DO_
}

void ArmyCodeReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  // repeated .com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce announces = 1;
  for (unsigned int i = 0, n = this->announces_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->announces(i), output);
  }

  // @@protoc_insertion_point(serialize_end:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
}

size_t ArmyCodeReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  size_t total_size = 0;

  // repeated .com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce announces = 1;
  {
    unsigned int count = this->announces_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->announces(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ArmyCodeReply::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ArmyCodeReply*>(&from));
}

void ArmyCodeReply::MergeFrom(const ArmyCodeReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  announces_.MergeFrom(from.announces_);
}

void ArmyCodeReply::CopyFrom(const ArmyCodeReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArmyCodeReply::IsInitialized() const {
  return true;
}

void ArmyCodeReply::Swap(ArmyCodeReply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ArmyCodeReply::InternalSwap(ArmyCodeReply* other) {
  announces_.UnsafeArenaSwap(&other->announces_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string ArmyCodeReply::GetTypeName() const {
  return "com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ArmyCodeReply

// repeated .com.yhsoftlab.app.cahelper.protobuf.ArmyCodeAnnounce announces = 1;
int ArmyCodeReply::announces_size() const {
  return announces_.size();
}
void ArmyCodeReply::clear_announces() {
  announces_.Clear();
}
const ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce& ArmyCodeReply::announces(int index) const {
  // @@protoc_insertion_point(field_get:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply.announces)
  return announces_.Get(index);
}
::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce* ArmyCodeReply::mutable_announces(int index) {
  // @@protoc_insertion_point(field_mutable:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply.announces)
  return announces_.Mutable(index);
}
::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce* ArmyCodeReply::add_announces() {
  // @@protoc_insertion_point(field_add:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply.announces)
  return announces_.Add();
}
::google::protobuf::RepeatedPtrField< ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce >*
ArmyCodeReply::mutable_announces() {
  // @@protoc_insertion_point(field_mutable_list:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply.announces)
  return &announces_;
}
const ::google::protobuf::RepeatedPtrField< ::com::yhsoftlab::app::cahelper::protobuf::ArmyCodeAnnounce >&
ArmyCodeReply::announces() const {
  // @@protoc_insertion_point(field_list:com.yhsoftlab.app.cahelper.protobuf.ArmyCodeReply.announces)
  return announces_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace cahelper
}  // namespace app
}  // namespace yhsoftlab
}  // namespace com

// @@protoc_insertion_point(global_scope)
