CREATE TABLE IF NOT EXISTS accounts(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE,
  password TEXT
);

CREATE TABLE IF NOT EXISTS cookies(
  accountId INTEGER REFERENCES accounts ON DELETE CASCADE UNIQUE ON CONFLICT REPLACE,
  pickle TEXT
);

CREATE TABLE IF NOT EXISTS fbids(
  accountId INTEGER REFERENCES accounts ON DELETE CASCADE UNIQUE ON CONFLICT REPLACE,
  fbid TEXT
);

CREATE TABLE IF NOT EXISTS igns(
  accountId INTEGER REFERENCES accounts ON DELETE CASCADE UNIQUE ON CONFLICT REPLACE,
  name TEXT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS levels(
  accountId INTEGER REFERENCES accounts ON DELETE CASCADE UNIQUE ON CONFLICT REPLACE,
  lvl INTEGER,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS arena_duel_result(
  player_fbid TEXT NOT NULL,
  enemy_fbid TEXT NOT NULL,
  win INTEGER DEFAULT 0,
  lose INTEGER DEFAULT 0,
  UNIQUE(player_fbid, enemy_fbid)
);
